name: code_projectv1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.1
  awesome_snackbar_content: ^0.1.4
  crypto: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/qr.png" # Asegúrate de que esta sea la ruta de tu icono

flutter:

  uses-material-design: true

  assets:
    - assets/
